--DATA INIT
INSERT INTO PRODUCT
VALUES (1001, 'candy', 'test1', 50);

INSERT INTO PRODUCT
VALUES (1002, 't-shirt', 'china11', 42);

INSERT INTO PRODUCT
VALUES (1003, 't-shirt', 'test1', 50);

--UPDATE
UPDATE PRODUCT SET MANUFACTURER_NAME='china' WHERE NAME='t-shirt';
SELECT * FROM PRODUCT;
--DELETE
DELETE FROM PRODUCT WHERE ID<1050;