--TASK2
CREATE TABLE MOVIE_STAT(
     MOVIE_ID NUMBER,
     CONSTRAINT MOVIE_STAT_ID_PK PRIMARY KEY (MOVIE_ID),
     RATING NUMBER(*,1) CHECK (RATING BETWEEN 1 AND 10),
     DOMESTIC_SALES NUMBER(*),
     INTERNATIONAL_SALES NUMBER(*)
);

--OPTIONAL
--MOVIE_STAT DATA INIT
INSERT INTO MOVIE_STAT
VALUES (1, 2.5, 55, 555);

INSERT INTO MOVIE_STAT
VALUES (2, 3.5, 555, 5455);

INSERT INTO MOVIE_STAT
VALUES (3, 9.5, 44555, 5333455);