--DATA INIT
INSERT INTO DEAL VALUES(3001, 10001, TO_DATE('06 2017', 'MM YYYY'));
INSERT INTO DEAL VALUES(3001, 101, TO_DATE('08 2018', 'MM YYYY'));
INSERT INTO DEAL VALUES(3002, 101, TO_DATE('08 2017', 'MM YYYY'));
INSERT INTO DEAL VALUES(3005, 24331, TO_DATE('07 2017', 'MM YYYY'));
INSERT INTO DEAL VALUES(3002, 24331, TO_DATE('08 2017', 'MM YYYY'));
INSERT INTO DEAL VALUES(3003, 5531, TO_DATE('08 2019', 'MM YYYY'));
INSERT INTO DEAL VALUES(3009, 24432, TO_DATE('08 2017', 'MM YYYY'));

DELETE FROM  DEAL;
-- имена клиентов, их город, имена менеджерова по продажам,
-- и их город, где сумма сделки была больше 10000
SELECT C.CUSTNAME AS CUSTOMER_NAME, C.CITY AS CUSTOMER_CITY ,
    S.NAME AS SALESMAN_NAME, S.CITY AS SALESMAN_CITY
FROM CUSTOMER C
JOIN SALESMAN S ON C.SALESMAN_ID=S.SALESMAN_ID
JOIN DEAL D ON D.CUSTOMER_ID=C.CUSTOMER_ID AND D.AMOUNT>10000;

--имена клиентов которые делали сделки в 2017-2018 годах
SELECT C.CUSTNAME
FROM CUSTOMER C
JOIN DEAL D ON D.CUSTOMER_ID = C.CUSTOMER_ID
    AND D.DATE_CREATED BETWEEN TO_DATE('2017/01/01 00:00:00', 'yyyy/mm/dd hh24:mi:ss')
        AND TO_DATE('2018/12/31 00:00:00', 'yyyy/mm/dd hh24:mi:ss')
GROUP BY C.CUSTNAME;

--второй способ
SELECT C.CUSTNAME
FROM CUSTOMER C
JOIN DEAL D ON D.CUSTOMER_ID = C.CUSTOMER_ID
WHERE D.DATE_CREATED BETWEEN TO_DATE('2017/01/01 00:00:00', 'yyyy/mm/dd hh24:mi:ss')
    AND TO_DATE('2018/12/31 00:00:00', 'yyyy/mm/dd hh24:mi:ss')
GROUP BY C.CUSTNAME;

--имя лучшего менеджера по продажам по сумме сделок за август 2017 года,
--выводить несколько имен, если таких менеджеров несколько
SELECT NAME, ALL_AMOUNT
FROM (SELECT S.NAME AS NAME, SUM(D.AMOUNT) AS ALL_AMOUNT
    FROM SALESMAN S
    JOIN CUSTOMER C ON S.SALESMAN_ID=C.SALESMAN_ID
    JOIN DEAL D ON D.CUSTOMER_ID=C.CUSTOMER_ID AND DATE_CREATED=TO_DATE('08 2017', 'MM YYYY')
    GROUP BY S.NAME)
WHERE ALL_AMOUNT=(SELECT MAX(ALL_AMOUNT)
                    FROM (SELECT S.NAME, SUM(D.AMOUNT) AS ALL_AMOUNT
                            FROM SALESMAN S
                            JOIN CUSTOMER C ON S.SALESMAN_ID=C.SALESMAN_ID
                            JOIN DEAL D ON D.CUSTOMER_ID=C.CUSTOMER_ID
                            GROUP BY S.NAME));