-- имена клиентов, их город, имена менеджерова по продажам,
-- и их город, где сумма сделки была больше 10000
SELECT C.CUSTNAME AS CUSTOMER_NAME, C.CITY AS CUSTOMER_CITY ,
    S.NAME AS SALESMAN_NAME, S.CITY AS SALESMAN_CITY
FROM CUSTOMER C
JOIN SALESMAN S ON C.SALESMAN_ID=S.SALESMAN_ID
JOIN DEAL D ON D.CUSTOMER_ID=C.CUSTOMER_ID AND D.AMOUNT>10000;


