CREATE TABLE ORDER_DETAILS(
    ORDER_ID NUMBER,
    CONSTRAINT ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    UNIT_PRICE NUMBER(*,2),
    QUANTITY NUMBER(*),
    DISCOUNT NUMBER(*,2)
);