CREATE TABLE MOVIE(
    ID NUMBER,
    CONSTRAINT MOVIE_PK PRIMARY KEY (ID),
    TITLE NVARCHAR2(50) UNIQUE NOT NULL,
    DIRECTOR NVARCHAR2(20) NOT NULL,
    CONSTRAINT CHECK_DIRECTOR_LENGTH CHECK (DIRECTOR <= 20),
    YEAR NUMBER(4) CHECK (YEAR BETWEEN 1900 AND 2020),
    LENGTH_MINS NUMBER,
    CONSTRAINT CHECK_LENGTH_MINS CHECK (LENGTH_MINS BETWEEN 10 and 200)
);