CREATE TABLE FORUM_POSTS(
    ID NUMBER,
    CONSTRAINT PK_FORUM_POST PRIMARY KEY (ID),
    ID_SUBCATEGORY NUMBER,
    CONSTRAINT FK_SUBCATEGORY FOREIGN KEY (ID_SUBCATEGORY) REFERENCES FORUM_SUBCATEGORIES (ID),
    ID_USER NUMBER,
    CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
    PARENT_POST NUMBER,
    CONSTRAINT FK_PARENT_POST FOREIGN KEY (PARENT_POST) REFERENCES FORUM_POSTS (ID),
    TITLE VARCHAR(90),
    CONTENT CLOB,
    --BOOLEAN ANALOGUE
    IS_POLL NUMBER(1) CHECK (IS_POLL IN (0,1)),
    DATE_CREATED TIMESTAMP,
    IP VARCHAR(20)
);