CREATE TABLE FORUM_SUBCATEGORIES(
     ID NUMBER,
     CONSTRAINT PK_FORUM_SUBCATEGORY PRIMARY KEY (ID),
     ID_CATEGORY NUMBER,
     CONSTRAINT FK_FORUM_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES FORUM_CATEGORIES(ID),
     TITLE VARCHAR(45),
     DESCRIPTION CLOB,
     DATE_CREATED TIMESTAMP,
     IP VARCHAR(20)
);