CREATE TABLE USERS(
    ID NUMBER,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    NICK VARCHAR(16),
    PASSWORD VARCHAR(128),
    EMAIL VARCHAR(128),
    DATE_CREATED TIMESTAMP,
    KARMA NUMBER(9,2),
    IP VARCHAR(20)
);