CREATE TABLE FORUM_POLLS_OPTIONS_VOTES(
    ID NUMBER,
    CONSTRAINT PK_FORUM_POLL_OPTION_VOTE PRIMARY KEY (ID),
    ID_POLL_OPTION NUMBER,
    CONSTRAINT FK_FORUM_POLLS_OPTIONS FOREIGN KEY (ID_POLL_OPTION) REFERENCES FORUM_POLLS_OPTIONS (ID),
    ID_USER NUMBER,
    CONSTRAINT FK_USERS FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
    DATE_CREATED TIMESTAMP,
    IP VARCHAR(20)
);