CREATE TABLE ORDERS(
    ORDER_ID NUMBER,
    CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
    CUSTOMER_ID NUMBER,
    CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    EMPLOYEE_ID NUMBER,
    CONSTRAINT EMPLOYEE_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    ORDER_DATE TIMESTAMP,
    REQUIRED_DATE TIMESTAMP,
    SHIPPED_DATE TIMESTAMP,
    --SHIPPER_ID?
    SHIP_VIA NUMBER,
    CONSTRAINT SHIPPER_FK FOREIGN KEY (SHIP_VIA) REFERENCES SHIPPERS(SHIPPER_ID),
    FREIGHT NUMBER(*,2),
    SHIP_NAME NVARCHAR2(50),
    SHIP_ADDRESS NVARCHAR2(100),
    SHIP_CITY NVARCHAR2(50),
    SHIP_REGION NVARCHAR2(50),
    SHIP_POSTAL_CODE NUMBER(*),
    SHiP_COUNTRY NVARCHAR2(50)
);