-- Измененяет PK таблицы Suppliers с SupplierID на Phone
ALTER TABLE PRODUCTS
DROP CONSTRAINT SUPPLIER_FK;

ALTER TABLE SUPPLIERS
DROP CONSTRAINT SUPPLIER_PK;

ALTER TABLE SUPPLIERS
ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY (PHONE);

ALTER TABLE PRODUCTS
ADD SUPPLIER_PHONE NUMBER(*);

ALTER TABLE PRODUCTS
ADD CONSTRAINT SUPPLIER_FK
FOREIGN KEY (SUPPLIER_PHONE) REFERENCES SUPPLIERS(PHONE);