CREATE TABLE ORDERS(
    ID NUMBER CHECK (ID <= 10000),
    CONSTRAINT ORDERS_PK PRIMARY KEY (ID),
    USER_ID NUMBER UNIQUE NOT NULL,
    --CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    ROOM_ID NUMBER UNIQUE NOT NULL,
    --CONSTRAINT ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID),
    DATE_FROM TIMESTAMP,
    DATE_TO TIMESTAMP,
    MONEY_PAID NUMBER(*, 2)
);